# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('fisrt_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
